# Generated by Django 5.2.5 on 2025-09-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_bites', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='comment',
            name='age_group',
            field=models.CharField(choices=[('6_months', '6+ Months'), ('8_months', '8+ Months'), ('10_months', '10+ Months'), ('12_months', '1 Year Old')], default='6_months', max_length=20),
        ),
    ]
