# Generated by Django 5.2.5 on 2025-09-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_bites', '0004_alter_comment_options_comment_age_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='age_group',
        ),
        migrations.AddField(
            model_name='post',
            name='age_group',
            field=models.CharField(choices=[('6_months', '6+ Months'), ('8_months', '8+ Months'), ('10_months', '10+ Months'), ('12_months', '1 Year Old')], default='6_months', max_length=20),
        ),
    ]
