# Generated by Django 4.2.23 on 2025-10-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_bites', '0011_post_approved_alter_post_slug_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
