# Generated by Django 5.2.5 on 2025-10-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_bites', '0012_remove_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='age_group',
            field=models.CharField(choices=[('6_months', '6 Months'), ('8_months', '8 Months'), ('10_months', '10 Months'), ('12_months', '12 Months')], default='6_months', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
