# Generated by Django 4.2.23 on 2025-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_bites', '0014_recipe_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age_group',
            field=models.CharField(choices=[('6_months', '6 Months'), ('8_months', '8 Months'), ('10_months', '10 Months'), ('12_months', '12 Months')], default='6_months', max_length=20),
        ),
    ]
