# Generated by Django 4.2.23 on 2025-11-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_bites', '0016_alter_comment_options_comment_edited_recipe_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
